apiVersion: catalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: users
name: users
spec:
  serviceClassName: users
  planName: default
  parameters:
    useProxy: true
---
apiVersion: catalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: inventory
name: inventory
spec: 
  serviceClassName: inventory
  planName: default
  parameters:
    useProxy: true
---
apiVersion: catalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: purchases
name: purchases
spec:
  serviceClassName: purchases
  planName: default
  parameters:
    useProxy: true
---
apiVersion: catalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: payments
name: payments
spec:
  serviceClassName: user-provided-service
  planName: default
  parameters:
    credentials:
      hostname: payments
      port: "80"
