apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstanceCredential
metadata:
  name: gcp-pubsub-binding
spec:
  instanceRef:
    name: gcp-pubsub-instance
  secretName: gcp-pubsub-credentials
  parameters:
    # The user should update the service account here to point to the service
    # account in their project they created for this demo.
    serviceAccount: "sc-bookstore-demo@${YOUR-PROJECT-HERE}.iam.gserviceaccount.com"
    roles: ["roles/pubsub.editor"]
