apiVersion: servicecatalog.k8s.io/v1alpha1
kind: ServiceInstance
metadata:
  name: payments
name: payments
spec:
  serviceClassName: user-provided-service
  planName: default
  parameters:
    credentials:
      hostname: payments
      port: "80"
