apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: purchases
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: purchases-service
        target_service: purchases-service
        targetService: purchases-service
        app: purchases
    spec:
      containers:
      - name: purchases-svc
        image: {{ .Values.image }}
        ports:
          - containerPort: 8080
        env:
          - name: SVC_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SVC_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

          # User service information from binding.
          - name: SVC_USERS_HOST
            valueFrom:
              secretKeyRef:
                name: purchases-users
                key: hostname
          - name: SVC_USERS_PORT
            valueFrom:
              secretKeyRef:
                name: purchases-users
                key: port

          # Bookstore service information from binding.
          - name: SVC_BOOKS_HOST
            valueFrom:
              secretKeyRef:
                name: purchases-inventory
                key: hostname
          - name: SVC_BOOKS_PORT
            valueFrom:
              secretKeyRef:
                name: purchases-inventory
                key: port
{{ if .Values.useProxy }}
      - name: kibbegcpnextproxy
        command:
        - /usr/local/bin/envoy
        - -l
        - debug
        - -c
        - /etc/envoy/envoy-esp.conf
        env:
        - name: target_service
          value: purchases
        - name: TARGET_SERVICE
          value: purchases
        - name: targetService
          value: purchases
        image: gcr.io/istio-testing/proxy:gcpnext
        ports:
        - containerPort: 9090
          name: kibbegcpnextproxyport
          protocol: TCP
        volumeMounts:
        - mountPath: /downward
          name: downwardapi
        - mountPath: /etc/envoy
          name: envoy-config
          readOnly: true
      volumes:
      - configMap:
          name: purchases-proxy-configmap-ingress
        name: envoy-config
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.annotations
            path: annotations
        name: downwardapi
{{ end }}
