apiVersion: v1
kind: Service
metadata:
  name: purchases
spec:
  ports:
  - port: 8080
    protocol: TCP
{{ if .Values.useProxy }}
    targetPort: 9090
{{ end }}
  selector:
    app: purchases
  type: LoadBalancer
