kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: helm-broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helm-broker
    spec:
      containers:
      - name: helm-broker
        image: gcr.io/kibbe-gcpnext/catalog/helm-broker:latest
        imagePullPolicy: Always
        args:
        - --registry_host
        - registry
        ports:
        - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: helm-broker
spec:
  selector:
    app: helm-broker
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
