apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: gcr.io/kibbe-gcpnext/catalog/registry:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
---
kind: Service
apiVersion: v1
metadata:
  name: registry
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 8001
    targetPort: 8001
